spring:
  cloud:
    azure:
      cosmos:
        database: auditlogDB
        endpoint: https://<cosmos_endpoint>:443/
        key: <secret_key>
        populate-query-metrics: true
      eventhubs:
        connection-string: Endpoint=sb://<endpoint.servicebus>/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=<shared-access-key>
        processor:
          checkpoint-store:
            account-name: <azure-storage-acc-name>
            account-key: <account-key>
            container-name: <eventhub-container-name>
    stream:
      default-binder: eventhubs
      function:
        definition: auditLogConsumer
      bindings:
        auditProducer-out-0:
          destination: data-audit-event
        auditLogConsumer-in-0:
          destination: data-audit-event
          group: $Default
      eventhubs:
        bindings:
          auditLogConsumer-in-0:
            consumer:
              checkpoint:
                mode: MANUAL
      poller:
        initial-delay: 0
        fixed-delay: 1000